package com.senprojectbackend1.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ExternalLinkAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExternalLinkAllPropertiesEquals(ExternalLink expected, ExternalLink actual) {
        assertExternalLinkAutoGeneratedPropertiesEquals(expected, actual);
        assertExternalLinkAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExternalLinkAllUpdatablePropertiesEquals(ExternalLink expected, ExternalLink actual) {
        assertExternalLinkUpdatableFieldsEquals(expected, actual);
        assertExternalLinkUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExternalLinkAutoGeneratedPropertiesEquals(ExternalLink expected, ExternalLink actual) {
        assertThat(actual)
            .as("Verify ExternalLink auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExternalLinkUpdatableFieldsEquals(ExternalLink expected, ExternalLink actual) {
        assertThat(actual)
            .as("Verify ExternalLink relevant properties")
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getUrl()).as("check url").isEqualTo(expected.getUrl()))
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExternalLinkUpdatableRelationshipsEquals(ExternalLink expected, ExternalLink actual) {
        assertThat(actual)
            .as("Verify ExternalLink relationships")
            .satisfies(a -> assertThat(a.getProject()).as("check project").isEqualTo(expected.getProject()));
    }
}
