# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: senprojectbackend1
services:
  app:
    image: mouhacisse007/senprojectbackend1:v2.0.6
    env_file:
      - .env
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - SPRING_APPLICATION_NAME=senprojectbackend1
      - SPRING_R2DBC_URL=r2dbc:postgresql://postgresql:5432/${POSTGRES_DB}
      - SPRING_R2DBC_USERNAME=${POSTGRES_USER}
      - SPRING_R2DBC_PASSWORD=${SPRING_R2DBC_PASSWORD}
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=https://senproject-keycloak-prod.duckdns.org/realms/jhipster
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
    ports:
      - '8081:8081'
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8081/management/health
      interval: 5s
      timeout: 5s
      retries: 40
    #    depends_on:
    #      postgresql:
    #        condition: service_healthy
    #      keycloak:
    #        condition: service_healthy
    networks:
      - app-network
  senprojectgateway:
    #    image: lyak008/senprojectgateway1:v1
    image: mouhacisse007/senprojectgateway1:v2.2.7
    env_file:
      - .env
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - SPRING_APPLICATION_NAME=senprojectgateway1
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=https://senproject-keycloak-prod.duckdns.org/realms/jhipster
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID=${GATEWAY_CLIENT_ID}
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=${GATEWAY_CLIENT_SECRET}
      - JHIPSTER_SLEEP=0
    ports:
      - '8080:8080'
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8080/management/health
      interval: 5s
      timeout: 5s
      retries: 40
    #    depends_on:
    #      keycloak:
    #        condition: service_healthy
    #    #      app:
    #    #        condition: service_healthy
    networks:
      - app-network
  postgresql:
    extends:
      file: ./postgresql.yml
      service: postgresql
    networks:
      - app-network
  keycloak:
    extends:
      file: ./keycloak.yml
      service: keycloak
    networks:
      - app-network
  keycloak-db:
    extends:
      file: ./keycloak.yml
      service: keycloak-db
    networks:
      - app-network

volumes:
  postgres-data:
    driver: local
  keycloak-db-data:
    driver: local

networks:
  app-network:
    driver: bridge
