# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: senprojectbackend1
services:
  app:
    image: lyak008/monapp:prod
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
      - SPRING_R2DBC_URL=r2dbc:postgresql://postgresql:5432/SenProjectBackend1
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://postgresql:5432/SenProjectBackend1
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=http://130.185.119.253:9080/realms/jhipster
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID=webapp
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=SPxQQpQZBvfPqd9BXwDNbN7SLKckYYcC
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka:9092
    ports:
      - '8081:8081'
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8081/management/health
      interval: 5s
      timeout: 5s
      retries: 40
    depends_on:
      postgresql:
        condition: service_healthy
      keycloak:
        condition: service_healthy
      jhipster-registry:
        condition: service_healthy
    networks:
      - app-network
  senprojectgateway:
    image: mouhacisse007/senprojectgateway1:v2
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=http://130.185.119.253:9080/realms/jhipster
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID=web_app
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=SPxQQpQZBvfPqd9BXwDNbN7SLKckYYcC
      - JHIPSTER_SLEEP=0
    ports:
      - '8080:8080'
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8080/management/health
      interval: 5s
      timeout: 5s
      retries: 40
    depends_on:
      keycloak:
        condition: service_healthy
      jhipster-registry:
        condition: service_healthy
    #      app:
    #        condition: service_healthy
    networks:
      - app-network
  postgresql:
    extends:
      file: ./postgresql.yml
      service: postgresql
    networks:
      - app-network
  keycloak:
    image: lyak008/senproject-keycloak-prod:latest
    command: 'start --import-realm'
    #    volumes:
    #      - ./realm-config:/opt/keycloak/data/import
    #      - ./realm-config/keycloak-health-check.sh:/opt/keycloak/health-check.sh
    #      - ./realm-config/keycloak-theme-sen-project.jar:/opt/keycloak/providers/keycloak-theme-sen-project.jar
    #    env_file:
    #      - ../../../.env
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://keycloak-db:5432/keycloak
      - KC_DB_USERNAME=keycloak_user
      - KC_DB_PASSWORD=keycloak_password_prod_2024
      - KC_HOSTNAME_STRICT=false
      - KC_HTTP_ENABLED=true
      - KC_HTTP_PORT=9080
      - KC_HTTPS_PORT=9443
      - KC_PROXY=edge
      - KC_HEALTH_ENABLED=true
      - KC_HTTP_MANAGEMENT_PORT=9990
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin_prod_2024
      - KC_CACHE=ispn
      - KC_LOG_LEVEL=INFO
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HEALTH_ENABLED=true

    ports:
      - '9080:9080'
      - '9443:9443'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9080/q/health/live']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    restart: unless-stopped
    depends_on:
      keycloak-db:
        condition: service_healthy
    networks:
      - app-network
    labels:
      org.springframework.boot.ignore: true
  keycloak-db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak_user
      - POSTGRES_PASSWORD=keycloak_password_prod_2024
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U keycloak_user -d keycloak']
      interval: 10s
      timeout: 5s
      retries: 5
  jhipster-registry:
    extends:
      file: ./jhipster-registry.yml
      service: jhipster-registry
    depends_on:
      keycloak:
        condition: service_healthy
    networks:
      - app-network
  kafka:
    extends:
      file: ./kafka.yml
      service: kafka
    networks:
      - app-network
volumes:
  keycloak-db-data:
    driver: local
networks:
  app-network:
    driver: bridge
