# This configuration is intended for local development purpose
name: senprojectbackend-local
services:
  app:
    image: lyak008/senprojectbackend:v1
    env_file:
      - .env
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=dev,api-docs
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - SPRING_APPLICATION_NAME=senprojectbackend1
      - SPRING_R2DBC_URL=r2dbc:postgresql://localhost:5432/${POSTGRES_DB}
      - SPRING_R2DBC_USERNAME=${POSTGRES_USER}
      - SPRING_R2DBC_PASSWORD=${SPRING_R2DBC_PASSWORD}
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=${KEYCLOAK_ISSUER_URI_DEV}
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
    ports:
      - '8081:8081'
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8081/management/health
      interval: 5s
      timeout: 5s
      retries: 40
    depends_on:
      postgresql:
        condition: service_healthy
    networks:
      - app-network
  senprojectgateway:
    image: mouhacisse007/senprojectgateway1:v2.1.6
    env_file:
      - .env
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=dev,api-docs
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - SPRING_APPLICATION_NAME=senprojectgateway1
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=${KEYCLOAK_ISSUER_URI_DEV}
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID=${GATEWAY_CLIENT_ID}
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=${GATEWAY_CLIENT_SECRET}
      - JHIPSTER_SLEEP=0
    ports:
      - '8080:8080'
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8080/management/health
      interval: 5s
      timeout: 5s
      retries: 40
    depends_on:
      keycloak:
        condition: service_healthy
    networks:
      - app-network
  postgresql:
    extends:
      file: ./postgresql.yml
      service: postgresql
    ports:
      - '5432:5432'
    networks:
      - app-network
  keycloak:
    extends:
      file: ./keycloak.yml
      service: keycloak
    ports:
      - '9081:8080'
    networks:
      - app-network
  keycloak-db:
    extends:
      file: ./keycloak.yml
      service: keycloak-db
    networks:
      - app-network

volumes:
  postgres-data:
    driver: local
  keycloak-db-data:
    driver: local

networks:
  app-network:
    driver: bridge
