# Ajoutez ceci à votre fichier docker-compose.yml ou créez un nouveau fichier kafdrop.yml
name: senprojectbackend1
services:
  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    restart: unless-stopped
    ports:
      - '9020:9000'
    environment:
      KAFKA_BROKERCONNECT: kafka:9092
      JVM_OPTS: '-Xms32M -Xmx64M'
networks:
  kafka-net:
    external: true
    name: senprojectbackend1_default
