# Configuration Keycloak pour Production
name: senprojectbackend1

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.3
    command: 'start --import-realm'
    env_file:
      - .env
    environment:
      # Base de données production (PostgreSQL)
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://keycloak-db:5432/${KEYCLOAK_DB_NAME}
      - KC_DB_USERNAME=${KEYCLOAK_DB_USERNAME}
      - KC_DB_PASSWORD=${KEYCLOAK_DB_PASSWORD}

      # Configuration réseau
      # Hostname configuration (fixed URLs via hostname-url)
      - KC_HOSTNAME_STRICT=false
      - KC_HTTP_ENABLED=true
      - KC_HTTP_PORT=8080
      # Sécurité
      - KC_PROXY_HEADERS=xforwarded

      # Monitoring
      - KC_HEALTH_ENABLED=true
      - KC_HTTP_MANAGEMENT_PORT=9990

      # Admin
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}

      # Performance
      - KC_CACHE=ispn

      # Logging
      - KC_LOG_LEVEL=INFO

    ports:
      - '9080:9080'

    healthcheck:
      test: ['CMD', '/opt/keycloak/bin/kc.sh', 'show-config']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

    restart: unless-stopped

    depends_on:
      keycloak-db:
        condition: service_healthy

    labels:
      org.springframework.boot.ignore: true

  keycloak-db:
    image: postgres:15-alpine
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${KEYCLOAK_DB_NAME}
      - POSTGRES_USER=${KEYCLOAK_DB_USERNAME}
      - POSTGRES_PASSWORD=${KEYCLOAK_DB_PASSWORD}
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${KEYCLOAK_DB_USERNAME} -d ${KEYCLOAK_DB_NAME}']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  keycloak-db-data:
    driver: local
