# Configuration Keycloak pour Production
name: senprojectbackend1
services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.2.3
    command: 'start --import-realm'
    volumes:
      - ./realm-config:/opt/keycloak/data/import
      - ./realm-config/keycloak-health-check.sh:/opt/keycloak/health-check.sh
      - ./realm-config/keycloak-theme-sen-project.jar:/opt/keycloak/providers/keycloak-theme-sen-project.jar
    env_file:
      - ../../../.env
    environment:
      # Base de données production (PostgreSQL)
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://keycloak-db:5432/keycloak
      - KC_DB_USERNAME=keycloak_user
      - KC_DB_PASSWORD=keycloak_password_prod_2024

      # Configuration réseau
      - KC_HOSTNAME_STRICT=false
      - KC_HTTP_ENABLED=true
      - KC_HTTP_PORT=9080
      - KC_HTTPS_PORT=9443

      # Sécurité
      - KC_PROXY=edge

      # Monitoring
      - KC_HEALTH_ENABLED=true
      - KC_HTTP_MANAGEMENT_PORT=9990

      # Admin
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin_prod_2024

      # Performance
      - KC_CACHE=ispn

      # Logging
      - KC_LOG_LEVEL=INFO

    ports:
      - 9080:9080
      - 9443:9443

    healthcheck:
      test: 'bash /opt/keycloak/health-check.sh'
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

    restart: unless-stopped




    labels:
      org.springframework.boot.ignore: true

  # Base de données PostgreSQL pour production


volumes:
  keycloak-db-data:
    driver: local


