create table public.engagement_project
(
    id         bigint generated by default as identity (start with 1500)
        primary key,
    type       varchar(255) not null,
    created_at timestamp    not null,
    user_id    varchar(255)
        constraint fk_engagement_project__user_id
            references public.user_profile,
    project_id bigint
        constraint fk_engagement_project__project_id
            references public.project
            on delete cascade
);

alter table public.engagement_project
    owner to "SenProjectBackend1";

